/* Automatically generated by /home/ljb/optee/cflat/test-program/instrumentation/hookit on 2016-12-12 21:01:07.596056, do not edit! */

#include "btbl.h"

__attribute__((section(".btbl"),unused)) struct btbl_entry btbl[] = {
	{0x00010d64,0x00010d84},
	{0x00010d8c,0x00010d68},
	{0x00010d98,0x00010da8},
	{0x00010da4,0x00010db0},
};
int len_btbl = sizeof(btbl)/sizeof(struct btbl_entry);
