/* Automatically generated by /home/ljb/optee/cflat/test-program/instrumentation/hookit on 2016-12-12 21:01:07.596265, do not edit! */

#include "ltbl.h"

__attribute__((section(".ltbl"),unused)) struct ltbl_entry ltbl[] = {
	{0x00010d68,0x00010d90},
};
int len_ltbl = sizeof(ltbl)/sizeof(struct ltbl_entry);
