/* Automatically generated by ./instrumentation/hookit on 2017-06-14 21:08:00.944142, do not edit! */

#include "ripte_helpers.h"

__attribute__((section(".ltbl"),unused)) struct ltbl_entry ltbl[] = {
};
int len_ltbl = 0;
